-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMftC6lnPjrckUI0U
rKbRAhYih0Bm3Y+cTdDyUkqfziigCgYIKoZIzj0DAQehRANCAATfMlQg4biz8d+s
9TqMenolfXXo/Ifwnh6XLkH8GpwA4U/io4TFotGnV2KBaPf06uKoO6SdRSNN+353
LSjxcV6j
-----END PRIVATE KEY-----